on: 
  tag:
    branches:
      - 'master'
      - 'dev'
      - 'development'
      - 'desarrollo'
      - 'pre'
      - 'staging'
      - 'stage'
name: deploy
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - name: get current branch
      run: echo ::set-env name=BRANCH::$(echo ${GITHUB_REF#refs/heads/})
    # - name: get current branch
    #   shell: bash
    #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
    #   id: get_branch

    - name: checkout code from branch
      uses: actions/checkout@v2
      with:
        ref: ${{env.BRANCH}}
        fetch-depth: 0

    - name: get actual tag
      run: echo ::set-env name=NEXT_TAG::$(./scripts/git/get_actual_tag.sh)
        
    - name: set latest docker tag
      run: echo ::set-env name=LATEST_DOCKER_TAG::$(. scripts/docker/set_docker_latest_by_branch.sh ${{env.BRANCH}})

    - name: build and push to docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: false
        tag_with_sha: false
        add_git_labels: true
        tags: ${{ env.NEXT_TAG }},${{env.LATEST_DOCKER_TAG}}
        #push: ${{ startsWith(github.ref, 'refs/tags/') }}
        # push: ${{ steps.get_branch.outputs.branch!='master'}}


        
